name: Check Dead Links

on:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight
  workflow_dispatch:
permissions: read-all

jobs:
  lychee:
    name: Check Dead Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Link Checker
        id: lychee
        continue-on-error: true
        uses: lycheeverse/lychee-action@8646ba30535128ac92d33dfc9133794bfdd9b411 # v2
        with:
          args: >-
            --verbose --no-progress
            --accept 200,202,403
            --exclude '^https?://(www|in|ca)\.indeed\.com/viewjob\?jk='
            --exclude '^https?://[^/]+\.wd[0-9]+\.myworkdayjobs\.com/job/'
            './**/*.md' './**/*.html'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != '0' && github.event_name != 'pull_request'
        uses: peter-evans/create-issue-from-file@fca9117c27cdc29c6c4db3b86c48e4115a786710 # v6
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
